dependencies:
  - cdsapi
  - numpy
  - pandas
  - netCDF4
  - xarray
  - matplotlib
  - cartopy
  - jupyterlab-myst
  - jupyterlab
  - rioxarray
  - regionmask
  - geopandas
  - tqdm
  - folium
  - plotly
  - IPython
  - pathlib 
  - json
  - ipywidgets